title: "Mathias Mahudo DODOU"
tagline: "Administrateur Systèmes & DevOps Junior"
description: "Portfolio DevOps Junior – Linux, Docker, CI/CD, Cloud"
url: "https://dodoumathias.github.io"
baseurl: ""

theme: jekyll-theme-cayman

author:
  name: "Mahudo Mathias DODOU"
  email: "dodoumathiasmahudo@gmail.com"
  location: "Calavi, Bénin"
  bio: "DevOps Junior | Linux • Docker • CI/CD • Cloud"

lang: fr
timezone: Africa/Porto-Novo

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /projects/:name/
