title: "Mathias Dodou"
description: "DevOps Engineer | Automatisation, Docker, CI/CD"
url: "https://dodoumathias.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: "Mathias Dodou"
  avatar: "/assets/img/profile.png"
  bio: "DevOps Engineer | Linux | Docker | CI/CD"

defaults:
  - scope:
      path: ""
    values:
      layout: single
